// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © realanthonyc https://www.tradingview.com/u/realanthonyc

//@version=6
// ------------------------------------------------------------------
//  DMI Symmetry (Directional Movement Index Symmetry)
//  On Github: https://github.com/realanthonyc/DMI-Symmetry
//  v1.3.2
// ------------------------------------------------------------------
indicator(title="DMI Symmetry", shorttitle="DMIS", format=format.price, precision=2, timeframe="", timeframe_gaps=true)

// === Inputs ===
// DI & ADX
len = input.int(14, title="DI length", minval=1, tooltip="DI length controls the tempo and smoothness of the DMI system:\n" + "Smaller value makes the DI lines more sensitive and volatile, giving frequent but noisier crossovers; larger value smooths them out, producing fewer, slower, but steadier lines.\n" + "Adjust this value per timeframe so the crossover frequency fits your analysis.")
emaSmooth = input.int(1, title="EMA smoothing for DI", minval=1, step=1, tooltip="Additional EMA smoothing for the DI lines\n" + "(1 means no smoothing)")
lensig = input.int(14, title="ADX smoothing", minval=1)
// Symmetry Line and Reference Band
midSmooth = input.int(9, title="Symmetry Line EMA smoothing", minval=1, step=1, group="Symmetry Line & Band", tooltip="The Symmetry Line reflects overall market activity or total momentum, while ADX measures directional consensus.\n" + "(1 means no smoothing)")
bandHalf = input.float(5.0, title="Reference Band's width (±)", minval=0, group="Symmetry Line & Band")

// === DMI Calculation ===
up = ta.change(high)
down = -ta.change(low)
plusDM = na(up)  ? na : (up > down and up > 0 ? up : 0)
minusDM = na(down) ? na : (down > up and down > 0 ? down : 0)
trur = ta.rma(ta.tr, len)
plusRaw = fixnan(100 * ta.rma(plusDM,  len) / trur)
minusRaw = fixnan(100 * ta.rma(minusDM, len) / trur)

plus = emaSmooth == 1 ? plusRaw  : ta.ema(plusRaw,  emaSmooth)
minus = emaSmooth == 1 ? minusRaw : ta.ema(minusRaw, emaSmooth)

sum = plus + minus
adx = 100 * ta.rma(math.abs(plus - minus) / (sum == 0 ? 1 : sum), lensig)

// === Symmetry Line Calculation ===
rawSymLine   = (plus + minus) / 2
finalSymLine = midSmooth == 1 ? rawSymLine : ta.ema(rawSymLine, midSmooth)
upperLevel = finalSymLine + bandHalf
lowerLevel = finalSymLine - bandHalf

// === Plotting ===
// ADX
plot(adx, title="ADX", color=color.new(#ffbb00, 80), style=plot.style_area, linewidth=1, display=display.none)
// Symmetry Line and Reference Band
plot(finalSymLine, title="Symmetry Line", color=color.new(#666666, 70), linewidth=1, style=plot.style_line)
pU = plot(upperLevel, title="Upper Band Line", color=color.new(#666666, 80), display=display.none)
pL = plot(lowerLevel, title="Lower Band Line", color=color.new(#666666, 80), display=display.none)
fill(pU, pL, color=color.new(#9eeaff, 80), title="Reference Band")
// DI
plot(plus,  title="+DI", color=color.rgb(145, 221, 95), linewidth=2)
plot(minus, title="-DI", color=color.rgb(255, 108, 108), linewidth=2)